name: Build and deploy a container to an Azure Function App

# env:
#   AZURE_WEBAPP_NAME: MY_WEBAPP_NAME   # set this to your application's name

on:
  workflow_dispatch:

permissions:
  contents: 'read'
  packages: 'write'
  id-token: write

env:
  AZURE_FUNCTIONAPP_NAME: stcgenaidevtrfna
  REGISTRY: stcgenaidevtrcon.azurecr.io
  TAG: devtrfunctionapp:${{ github.run_id }}

jobs:
  build:
    name: "Build Image"
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: "Build image"
        run: |
          cd azure_functions
          docker build -t $REGISTRY/$TAG .
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: "Login to ACR"
        run: |
          cd azure_functions
          set -euo pipefail
          # see /2021/09/logging-into-acr-in-github-actions/
          # see https://github.com/Azure/acr/blob/main/docs/AAD-OAuth.md#calling-post-oauth2exchange-to-get-an-acr-refresh-token
          access_token=$(az account get-access-token --query accessToken -o tsv)
          refresh_token=$(curl https://$REGISTRY/oauth2/exchange -v -d "grant_type=access_token&service=$REGISTRY&access_token=$access_token" | jq -r .refresh_token)
          # The null GUID 0000... tells the container registry that this is an ACR refresh token during the login flow
          docker login -u 00000000-0000-0000-0000-000000000000 --password-stdin $REGISTRY <<< "$refresh_token"
      - name: "Push image to ACR"
        run: |
          cd azure_functions
          docker push $REGISTRY/$TAG

  deploy:
    name: "Deploy to Azure Function App"
    runs-on: ubuntu-latest
    environment: dev
    needs: build
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run Azure Functions Container Action'
        uses: Azure/functions-container-action@v1
        id: functionapp
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          image: ${{ env.REGISTRY }}/${{ env.TAG }}

